/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PaymentResultRouteImport } from './routes/payment-result'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminSetupRouteImport } from './routes/_authenticated/admin-setup'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedMyExamsRouteImport } from './routes/_authenticated/my-exams'
import { Route as AuthenticatedMyOrdersRouteImport } from './routes/_authenticated/my-orders'
import { Route as AuthenticatedMyResultsRouteImport } from './routes/_authenticated/my-results'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAiRouteImport } from './routes/admin/ai'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminHealthRouteImport } from './routes/admin/health'
import { Route as AdminNewsletterRouteImport } from './routes/admin/newsletter'
import { Route as AdminNewsletterDeliveriesRouteImport } from './routes/admin/newsletter-deliveries'
import { Route as AdminNewsletterSubscribersRouteImport } from './routes/admin/newsletter-subscribers'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminPlansRouteImport } from './routes/admin/plans'
import { Route as AdminQuestionsRouteImport } from './routes/admin/questions'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminReportsQuestionsRouteImport } from './routes/admin/reports-questions'
import { Route as AdminResultsRouteImport } from './routes/admin/results'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSmsRouteImport } from './routes/admin/sms'
import { Route as AdminSubjectsRouteImport } from './routes/admin/subjects'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as InviteSlugRouteImport } from './routes/invite.$slug'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as NewsletterManageRouteImport } from './routes/newsletter.manage'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as AuthenticatedPracticeIndexRouteImport } from './routes/_authenticated/practice.index'
import { Route as AuthenticatedPracticeSessionIdRouteImport } from './routes/_authenticated/practice.$sessionId'
import { Route as AdminBulkImportIndexRouteImport } from './routes/admin/bulk-import/index'
import { Route as AdminBulkImportBatchIdRouteImport } from './routes/admin/bulk-import/$batchId'
import { Route as AdminBulkImportHistoryRouteImport } from './routes/admin/bulk-import/history'
import { Route as AdminExamsIndexRouteImport } from './routes/admin/exams/index'
import { Route as AdminExamsIdRouteImport } from './routes/admin/exams/$id'
import { Route as AdminExamsNewRouteImport } from './routes/admin/exams/new'
import { Route as AdminShopIndexRouteImport } from './routes/admin/shop/index'
import { Route as AdminShopCategoriesRouteImport } from './routes/admin/shop/categories'
import { Route as AdminShopCouponsRouteImport } from './routes/admin/shop/coupons'
import { Route as AdminShopOrdersRouteImport } from './routes/admin/shop/orders'
import { Route as AdminShopProductsRouteImport } from './routes/admin/shop/products'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users/$id'
import { Route as AuthenticatedExamSlugIndexRouteImport } from './routes/_authenticated/exam.$slug.index'
import { Route as AuthenticatedExamSlugAttemptRouteImport } from './routes/_authenticated/exam.$slug.attempt'
import { Route as AuthenticatedExamSlugPracticeRouteImport } from './routes/_authenticated/exam.$slug.practice'
import { Route as AuthenticatedExamSlugResultRouteImport } from './routes/_authenticated/exam.$slug.result'
import { Route as ApiPublicNewsletterDigestProcessQueueRouteImport } from './routes/api/public/newsletter-digest.process-queue'
import { Route as ApiPublicNewsletterProcessQueueRouteImport } from './routes/api/public/newsletter.process-queue'
import { Route as ApiPublicWeeklyProgressProcessQueueRouteImport } from './routes/api/public/weekly-progress.process-queue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentResultRoute = PaymentResultRouteImport.update({
  id: '/payment-result',
  path: '/payment-result',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSetupRoute = AuthenticatedAdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyExamsRoute = AuthenticatedMyExamsRouteImport.update({
  id: '/my-exams',
  path: '/my-exams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyOrdersRoute = AuthenticatedMyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyResultsRoute = AuthenticatedMyResultsRouteImport.update({
  id: '/my-results',
  path: '/my-results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsletterDeliveriesRoute =
  AdminNewsletterDeliveriesRouteImport.update({
    id: '/newsletter-deliveries',
    path: '/newsletter-deliveries',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminNewsletterSubscribersRoute =
  AdminNewsletterSubscribersRouteImport.update({
    id: '/newsletter-subscribers',
    path: '/newsletter-subscribers',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsQuestionsRoute = AdminReportsQuestionsRouteImport.update({
  id: '/reports-questions',
  path: '/reports-questions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSmsRoute = AdminSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const InviteSlugRoute = InviteSlugRouteImport.update({
  id: '/invite/$slug',
  path: '/invite/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterManageRoute = NewsletterManageRouteImport.update({
  id: '/newsletter/manage',
  path: '/newsletter/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPracticeIndexRoute =
  AuthenticatedPracticeIndexRouteImport.update({
    id: '/practice/',
    path: '/practice/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeSessionIdRoute =
  AuthenticatedPracticeSessionIdRouteImport.update({
    id: '/practice/$sessionId',
    path: '/practice/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminBulkImportIndexRoute = AdminBulkImportIndexRouteImport.update({
  id: '/bulk-import/',
  path: '/bulk-import/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBulkImportBatchIdRoute = AdminBulkImportBatchIdRouteImport.update({
  id: '/bulk-import/$batchId',
  path: '/bulk-import/$batchId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBulkImportHistoryRoute = AdminBulkImportHistoryRouteImport.update({
  id: '/bulk-import/history',
  path: '/bulk-import/history',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExamsIndexRoute = AdminExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExamsIdRoute = AdminExamsIdRouteImport.update({
  id: '/exams/$id',
  path: '/exams/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExamsNewRoute = AdminExamsNewRouteImport.update({
  id: '/exams/new',
  path: '/exams/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShopIndexRoute = AdminShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShopCategoriesRoute = AdminShopCategoriesRouteImport.update({
  id: '/shop/categories',
  path: '/shop/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShopCouponsRoute = AdminShopCouponsRouteImport.update({
  id: '/shop/coupons',
  path: '/shop/coupons',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShopOrdersRoute = AdminShopOrdersRouteImport.update({
  id: '/shop/orders',
  path: '/shop/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShopProductsRoute = AdminShopProductsRouteImport.update({
  id: '/shop/products',
  path: '/shop/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedExamSlugIndexRoute =
  AuthenticatedExamSlugIndexRouteImport.update({
    id: '/exam/$slug/',
    path: '/exam/$slug/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamSlugAttemptRoute =
  AuthenticatedExamSlugAttemptRouteImport.update({
    id: '/exam/$slug/attempt',
    path: '/exam/$slug/attempt',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamSlugPracticeRoute =
  AuthenticatedExamSlugPracticeRouteImport.update({
    id: '/exam/$slug/practice',
    path: '/exam/$slug/practice',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamSlugResultRoute =
  AuthenticatedExamSlugResultRouteImport.update({
    id: '/exam/$slug/result',
    path: '/exam/$slug/result',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicNewsletterDigestProcessQueueRoute =
  ApiPublicNewsletterDigestProcessQueueRouteImport.update({
    id: '/api/public/newsletter-digest/process-queue',
    path: '/api/public/newsletter-digest/process-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNewsletterProcessQueueRoute =
  ApiPublicNewsletterProcessQueueRouteImport.update({
    id: '/api/public/newsletter/process-queue',
    path: '/api/public/newsletter/process-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWeeklyProgressProcessQueueRoute =
  ApiPublicWeeklyProgressProcessQueueRouteImport.update({
    id: '/api/public/weekly-progress/process-queue',
    path: '/api/public/weekly-progress/process-queue',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/payment-result': typeof PaymentResultRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin-setup': typeof AuthenticatedAdminSetupRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/my-exams': typeof AuthenticatedMyExamsRoute
  '/my-orders': typeof AuthenticatedMyOrdersRoute
  '/my-results': typeof AuthenticatedMyResultsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/newsletter-deliveries': typeof AdminNewsletterDeliveriesRoute
  '/admin/newsletter-subscribers': typeof AdminNewsletterSubscribersRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reports-questions': typeof AdminReportsQuestionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/invite/$slug': typeof InviteSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/newsletter/manage': typeof NewsletterManageRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/practice/$sessionId': typeof AuthenticatedPracticeSessionIdRoute
  '/admin/bulk-import/$batchId': typeof AdminBulkImportBatchIdRoute
  '/admin/bulk-import/history': typeof AdminBulkImportHistoryRoute
  '/admin/exams/$id': typeof AdminExamsIdRoute
  '/admin/exams/new': typeof AdminExamsNewRoute
  '/admin/shop/categories': typeof AdminShopCategoriesRoute
  '/admin/shop/coupons': typeof AdminShopCouponsRoute
  '/admin/shop/orders': typeof AdminShopOrdersRoute
  '/admin/shop/products': typeof AdminShopProductsRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/practice/': typeof AuthenticatedPracticeIndexRoute
  '/admin/bulk-import/': typeof AdminBulkImportIndexRoute
  '/admin/exams/': typeof AdminExamsIndexRoute
  '/admin/shop/': typeof AdminShopIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/exam/$slug/attempt': typeof AuthenticatedExamSlugAttemptRoute
  '/exam/$slug/practice': typeof AuthenticatedExamSlugPracticeRoute
  '/exam/$slug/result': typeof AuthenticatedExamSlugResultRoute
  '/api/public/newsletter-digest/process-queue': typeof ApiPublicNewsletterDigestProcessQueueRoute
  '/api/public/newsletter/process-queue': typeof ApiPublicNewsletterProcessQueueRoute
  '/api/public/weekly-progress/process-queue': typeof ApiPublicWeeklyProgressProcessQueueRoute
  '/exam/$slug/': typeof AuthenticatedExamSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/payment-result': typeof PaymentResultRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin-setup': typeof AuthenticatedAdminSetupRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/my-exams': typeof AuthenticatedMyExamsRoute
  '/my-orders': typeof AuthenticatedMyOrdersRoute
  '/my-results': typeof AuthenticatedMyResultsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/newsletter-deliveries': typeof AdminNewsletterDeliveriesRoute
  '/admin/newsletter-subscribers': typeof AdminNewsletterSubscribersRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reports-questions': typeof AdminReportsQuestionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/invite/$slug': typeof InviteSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/newsletter/manage': typeof NewsletterManageRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin': typeof AdminIndexRoute
  '/news': typeof NewsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/practice/$sessionId': typeof AuthenticatedPracticeSessionIdRoute
  '/admin/bulk-import/$batchId': typeof AdminBulkImportBatchIdRoute
  '/admin/bulk-import/history': typeof AdminBulkImportHistoryRoute
  '/admin/exams/$id': typeof AdminExamsIdRoute
  '/admin/exams/new': typeof AdminExamsNewRoute
  '/admin/shop/categories': typeof AdminShopCategoriesRoute
  '/admin/shop/coupons': typeof AdminShopCouponsRoute
  '/admin/shop/orders': typeof AdminShopOrdersRoute
  '/admin/shop/products': typeof AdminShopProductsRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/practice': typeof AuthenticatedPracticeIndexRoute
  '/admin/bulk-import': typeof AdminBulkImportIndexRoute
  '/admin/exams': typeof AdminExamsIndexRoute
  '/admin/shop': typeof AdminShopIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/exam/$slug/attempt': typeof AuthenticatedExamSlugAttemptRoute
  '/exam/$slug/practice': typeof AuthenticatedExamSlugPracticeRoute
  '/exam/$slug/result': typeof AuthenticatedExamSlugResultRoute
  '/api/public/newsletter-digest/process-queue': typeof ApiPublicNewsletterDigestProcessQueueRoute
  '/api/public/newsletter/process-queue': typeof ApiPublicNewsletterProcessQueueRoute
  '/api/public/weekly-progress/process-queue': typeof ApiPublicWeeklyProgressProcessQueueRoute
  '/exam/$slug': typeof AuthenticatedExamSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/payment-result': typeof PaymentResultRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin-setup': typeof AuthenticatedAdminSetupRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRoute
  '/_authenticated/my-exams': typeof AuthenticatedMyExamsRoute
  '/_authenticated/my-orders': typeof AuthenticatedMyOrdersRoute
  '/_authenticated/my-results': typeof AuthenticatedMyResultsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/newsletter-deliveries': typeof AdminNewsletterDeliveriesRoute
  '/admin/newsletter-subscribers': typeof AdminNewsletterSubscribersRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reports-questions': typeof AdminReportsQuestionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/invite/$slug': typeof InviteSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/newsletter/manage': typeof NewsletterManageRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/_authenticated/practice/$sessionId': typeof AuthenticatedPracticeSessionIdRoute
  '/admin/bulk-import/$batchId': typeof AdminBulkImportBatchIdRoute
  '/admin/bulk-import/history': typeof AdminBulkImportHistoryRoute
  '/admin/exams/$id': typeof AdminExamsIdRoute
  '/admin/exams/new': typeof AdminExamsNewRoute
  '/admin/shop/categories': typeof AdminShopCategoriesRoute
  '/admin/shop/coupons': typeof AdminShopCouponsRoute
  '/admin/shop/orders': typeof AdminShopOrdersRoute
  '/admin/shop/products': typeof AdminShopProductsRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/_authenticated/practice/': typeof AuthenticatedPracticeIndexRoute
  '/admin/bulk-import/': typeof AdminBulkImportIndexRoute
  '/admin/exams/': typeof AdminExamsIndexRoute
  '/admin/shop/': typeof AdminShopIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/_authenticated/exam/$slug/attempt': typeof AuthenticatedExamSlugAttemptRoute
  '/_authenticated/exam/$slug/practice': typeof AuthenticatedExamSlugPracticeRoute
  '/_authenticated/exam/$slug/result': typeof AuthenticatedExamSlugResultRoute
  '/api/public/newsletter-digest/process-queue': typeof ApiPublicNewsletterDigestProcessQueueRoute
  '/api/public/newsletter/process-queue': typeof ApiPublicNewsletterProcessQueueRoute
  '/api/public/weekly-progress/process-queue': typeof ApiPublicWeeklyProgressProcessQueueRoute
  '/_authenticated/exam/$slug/': typeof AuthenticatedExamSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/payment-result'
    | '/signup'
    | '/sitemap.xml'
    | '/admin-setup'
    | '/cart'
    | '/checkout'
    | '/coach'
    | '/dashboard'
    | '/exams'
    | '/my-exams'
    | '/my-orders'
    | '/my-results'
    | '/profile'
    | '/subscription'
    | '/admin/ai'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/health'
    | '/admin/newsletter'
    | '/admin/newsletter-deliveries'
    | '/admin/newsletter-subscribers'
    | '/admin/organizations'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/reports-questions'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/sms'
    | '/admin/subjects'
    | '/admin/subscriptions'
    | '/invite/$slug'
    | '/news/$slug'
    | '/newsletter/manage'
    | '/payment/callback'
    | '/shop/$slug'
    | '/admin/'
    | '/news/'
    | '/shop/'
    | '/practice/$sessionId'
    | '/admin/bulk-import/$batchId'
    | '/admin/bulk-import/history'
    | '/admin/exams/$id'
    | '/admin/exams/new'
    | '/admin/shop/categories'
    | '/admin/shop/coupons'
    | '/admin/shop/orders'
    | '/admin/shop/products'
    | '/admin/users/$id'
    | '/practice/'
    | '/admin/bulk-import/'
    | '/admin/exams/'
    | '/admin/shop/'
    | '/admin/users/'
    | '/exam/$slug/attempt'
    | '/exam/$slug/practice'
    | '/exam/$slug/result'
    | '/api/public/newsletter-digest/process-queue'
    | '/api/public/newsletter/process-queue'
    | '/api/public/weekly-progress/process-queue'
    | '/exam/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/payment-result'
    | '/signup'
    | '/sitemap.xml'
    | '/admin-setup'
    | '/cart'
    | '/checkout'
    | '/coach'
    | '/dashboard'
    | '/exams'
    | '/my-exams'
    | '/my-orders'
    | '/my-results'
    | '/profile'
    | '/subscription'
    | '/admin/ai'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/health'
    | '/admin/newsletter'
    | '/admin/newsletter-deliveries'
    | '/admin/newsletter-subscribers'
    | '/admin/organizations'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/reports-questions'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/sms'
    | '/admin/subjects'
    | '/admin/subscriptions'
    | '/invite/$slug'
    | '/news/$slug'
    | '/newsletter/manage'
    | '/payment/callback'
    | '/shop/$slug'
    | '/admin'
    | '/news'
    | '/shop'
    | '/practice/$sessionId'
    | '/admin/bulk-import/$batchId'
    | '/admin/bulk-import/history'
    | '/admin/exams/$id'
    | '/admin/exams/new'
    | '/admin/shop/categories'
    | '/admin/shop/coupons'
    | '/admin/shop/orders'
    | '/admin/shop/products'
    | '/admin/users/$id'
    | '/practice'
    | '/admin/bulk-import'
    | '/admin/exams'
    | '/admin/shop'
    | '/admin/users'
    | '/exam/$slug/attempt'
    | '/exam/$slug/practice'
    | '/exam/$slug/result'
    | '/api/public/newsletter-digest/process-queue'
    | '/api/public/newsletter/process-queue'
    | '/api/public/weekly-progress/process-queue'
    | '/exam/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/payment-result'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/admin-setup'
    | '/_authenticated/cart'
    | '/_authenticated/checkout'
    | '/_authenticated/coach'
    | '/_authenticated/dashboard'
    | '/_authenticated/exams'
    | '/_authenticated/my-exams'
    | '/_authenticated/my-orders'
    | '/_authenticated/my-results'
    | '/_authenticated/profile'
    | '/_authenticated/subscription'
    | '/admin/ai'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/health'
    | '/admin/newsletter'
    | '/admin/newsletter-deliveries'
    | '/admin/newsletter-subscribers'
    | '/admin/organizations'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/reports-questions'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/sms'
    | '/admin/subjects'
    | '/admin/subscriptions'
    | '/invite/$slug'
    | '/news/$slug'
    | '/newsletter/manage'
    | '/payment/callback'
    | '/shop/$slug'
    | '/admin/'
    | '/news/'
    | '/shop/'
    | '/_authenticated/practice/$sessionId'
    | '/admin/bulk-import/$batchId'
    | '/admin/bulk-import/history'
    | '/admin/exams/$id'
    | '/admin/exams/new'
    | '/admin/shop/categories'
    | '/admin/shop/coupons'
    | '/admin/shop/orders'
    | '/admin/shop/products'
    | '/admin/users/$id'
    | '/_authenticated/practice/'
    | '/admin/bulk-import/'
    | '/admin/exams/'
    | '/admin/shop/'
    | '/admin/users/'
    | '/_authenticated/exam/$slug/attempt'
    | '/_authenticated/exam/$slug/practice'
    | '/_authenticated/exam/$slug/result'
    | '/api/public/newsletter-digest/process-queue'
    | '/api/public/newsletter/process-queue'
    | '/api/public/weekly-progress/process-queue'
    | '/_authenticated/exam/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PaymentResultRoute: typeof PaymentResultRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  InviteSlugRoute: typeof InviteSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsletterManageRoute: typeof NewsletterManageRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  ShopSlugRoute: typeof ShopSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ApiPublicNewsletterDigestProcessQueueRoute: typeof ApiPublicNewsletterDigestProcessQueueRoute
  ApiPublicNewsletterProcessQueueRoute: typeof ApiPublicNewsletterProcessQueueRoute
  ApiPublicWeeklyProgressProcessQueueRoute: typeof ApiPublicWeeklyProgressProcessQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-result': {
      id: '/payment-result'
      path: '/payment-result'
      fullPath: '/payment-result'
      preLoaderRoute: typeof PaymentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin-setup': {
      id: '/_authenticated/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AuthenticatedAdminSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-exams': {
      id: '/_authenticated/my-exams'
      path: '/my-exams'
      fullPath: '/my-exams'
      preLoaderRoute: typeof AuthenticatedMyExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-orders': {
      id: '/_authenticated/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof AuthenticatedMyOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-results': {
      id: '/_authenticated/my-results'
      path: '/my-results'
      fullPath: '/my-results'
      preLoaderRoute: typeof AuthenticatedMyResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/newsletter-deliveries': {
      id: '/admin/newsletter-deliveries'
      path: '/newsletter-deliveries'
      fullPath: '/admin/newsletter-deliveries'
      preLoaderRoute: typeof AdminNewsletterDeliveriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/newsletter-subscribers': {
      id: '/admin/newsletter-subscribers'
      path: '/newsletter-subscribers'
      fullPath: '/admin/newsletter-subscribers'
      preLoaderRoute: typeof AdminNewsletterSubscribersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports-questions': {
      id: '/admin/reports-questions'
      path: '/reports-questions'
      fullPath: '/admin/reports-questions'
      preLoaderRoute: typeof AdminReportsQuestionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sms': {
      id: '/admin/sms'
      path: '/sms'
      fullPath: '/admin/sms'
      preLoaderRoute: typeof AdminSmsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/invite/$slug': {
      id: '/invite/$slug'
      path: '/invite/$slug'
      fullPath: '/invite/$slug'
      preLoaderRoute: typeof InviteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/manage': {
      id: '/newsletter/manage'
      path: '/newsletter/manage'
      fullPath: '/newsletter/manage'
      preLoaderRoute: typeof NewsletterManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/practice/': {
      id: '/_authenticated/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof AuthenticatedPracticeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/$sessionId': {
      id: '/_authenticated/practice/$sessionId'
      path: '/practice/$sessionId'
      fullPath: '/practice/$sessionId'
      preLoaderRoute: typeof AuthenticatedPracticeSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/bulk-import/': {
      id: '/admin/bulk-import/'
      path: '/bulk-import'
      fullPath: '/admin/bulk-import/'
      preLoaderRoute: typeof AdminBulkImportIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bulk-import/$batchId': {
      id: '/admin/bulk-import/$batchId'
      path: '/bulk-import/$batchId'
      fullPath: '/admin/bulk-import/$batchId'
      preLoaderRoute: typeof AdminBulkImportBatchIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bulk-import/history': {
      id: '/admin/bulk-import/history'
      path: '/bulk-import/history'
      fullPath: '/admin/bulk-import/history'
      preLoaderRoute: typeof AdminBulkImportHistoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/exams/': {
      id: '/admin/exams/'
      path: '/exams'
      fullPath: '/admin/exams/'
      preLoaderRoute: typeof AdminExamsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/exams/$id': {
      id: '/admin/exams/$id'
      path: '/exams/$id'
      fullPath: '/admin/exams/$id'
      preLoaderRoute: typeof AdminExamsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/exams/new': {
      id: '/admin/exams/new'
      path: '/exams/new'
      fullPath: '/admin/exams/new'
      preLoaderRoute: typeof AdminExamsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shop/': {
      id: '/admin/shop/'
      path: '/shop'
      fullPath: '/admin/shop/'
      preLoaderRoute: typeof AdminShopIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shop/categories': {
      id: '/admin/shop/categories'
      path: '/shop/categories'
      fullPath: '/admin/shop/categories'
      preLoaderRoute: typeof AdminShopCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shop/coupons': {
      id: '/admin/shop/coupons'
      path: '/shop/coupons'
      fullPath: '/admin/shop/coupons'
      preLoaderRoute: typeof AdminShopCouponsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shop/orders': {
      id: '/admin/shop/orders'
      path: '/shop/orders'
      fullPath: '/admin/shop/orders'
      preLoaderRoute: typeof AdminShopOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shop/products': {
      id: '/admin/shop/products'
      path: '/shop/products'
      fullPath: '/admin/shop/products'
      preLoaderRoute: typeof AdminShopProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/exam/$slug/': {
      id: '/_authenticated/exam/$slug/'
      path: '/exam/$slug'
      fullPath: '/exam/$slug/'
      preLoaderRoute: typeof AuthenticatedExamSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam/$slug/attempt': {
      id: '/_authenticated/exam/$slug/attempt'
      path: '/exam/$slug/attempt'
      fullPath: '/exam/$slug/attempt'
      preLoaderRoute: typeof AuthenticatedExamSlugAttemptRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam/$slug/practice': {
      id: '/_authenticated/exam/$slug/practice'
      path: '/exam/$slug/practice'
      fullPath: '/exam/$slug/practice'
      preLoaderRoute: typeof AuthenticatedExamSlugPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam/$slug/result': {
      id: '/_authenticated/exam/$slug/result'
      path: '/exam/$slug/result'
      fullPath: '/exam/$slug/result'
      preLoaderRoute: typeof AuthenticatedExamSlugResultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/newsletter-digest/process-queue': {
      id: '/api/public/newsletter-digest/process-queue'
      path: '/api/public/newsletter-digest/process-queue'
      fullPath: '/api/public/newsletter-digest/process-queue'
      preLoaderRoute: typeof ApiPublicNewsletterDigestProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter/process-queue': {
      id: '/api/public/newsletter/process-queue'
      path: '/api/public/newsletter/process-queue'
      fullPath: '/api/public/newsletter/process-queue'
      preLoaderRoute: typeof ApiPublicNewsletterProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/weekly-progress/process-queue': {
      id: '/api/public/weekly-progress/process-queue'
      path: '/api/public/weekly-progress/process-queue'
      fullPath: '/api/public/weekly-progress/process-queue'
      preLoaderRoute: typeof ApiPublicWeeklyProgressProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminSetupRoute: typeof AuthenticatedAdminSetupRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRoute
  AuthenticatedMyExamsRoute: typeof AuthenticatedMyExamsRoute
  AuthenticatedMyOrdersRoute: typeof AuthenticatedMyOrdersRoute
  AuthenticatedMyResultsRoute: typeof AuthenticatedMyResultsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedPracticeSessionIdRoute: typeof AuthenticatedPracticeSessionIdRoute
  AuthenticatedPracticeIndexRoute: typeof AuthenticatedPracticeIndexRoute
  AuthenticatedExamSlugAttemptRoute: typeof AuthenticatedExamSlugAttemptRoute
  AuthenticatedExamSlugPracticeRoute: typeof AuthenticatedExamSlugPracticeRoute
  AuthenticatedExamSlugResultRoute: typeof AuthenticatedExamSlugResultRoute
  AuthenticatedExamSlugIndexRoute: typeof AuthenticatedExamSlugIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminSetupRoute: AuthenticatedAdminSetupRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRoute,
  AuthenticatedMyExamsRoute: AuthenticatedMyExamsRoute,
  AuthenticatedMyOrdersRoute: AuthenticatedMyOrdersRoute,
  AuthenticatedMyResultsRoute: AuthenticatedMyResultsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedPracticeSessionIdRoute: AuthenticatedPracticeSessionIdRoute,
  AuthenticatedPracticeIndexRoute: AuthenticatedPracticeIndexRoute,
  AuthenticatedExamSlugAttemptRoute: AuthenticatedExamSlugAttemptRoute,
  AuthenticatedExamSlugPracticeRoute: AuthenticatedExamSlugPracticeRoute,
  AuthenticatedExamSlugResultRoute: AuthenticatedExamSlugResultRoute,
  AuthenticatedExamSlugIndexRoute: AuthenticatedExamSlugIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminNewsletterDeliveriesRoute: typeof AdminNewsletterDeliveriesRoute
  AdminNewsletterSubscribersRoute: typeof AdminNewsletterSubscribersRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReportsQuestionsRoute: typeof AdminReportsQuestionsRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSmsRoute: typeof AdminSmsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBulkImportBatchIdRoute: typeof AdminBulkImportBatchIdRoute
  AdminBulkImportHistoryRoute: typeof AdminBulkImportHistoryRoute
  AdminExamsIdRoute: typeof AdminExamsIdRoute
  AdminExamsNewRoute: typeof AdminExamsNewRoute
  AdminShopCategoriesRoute: typeof AdminShopCategoriesRoute
  AdminShopCouponsRoute: typeof AdminShopCouponsRoute
  AdminShopOrdersRoute: typeof AdminShopOrdersRoute
  AdminShopProductsRoute: typeof AdminShopProductsRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminBulkImportIndexRoute: typeof AdminBulkImportIndexRoute
  AdminExamsIndexRoute: typeof AdminExamsIndexRoute
  AdminShopIndexRoute: typeof AdminShopIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminNewsletterDeliveriesRoute: AdminNewsletterDeliveriesRoute,
  AdminNewsletterSubscribersRoute: AdminNewsletterSubscribersRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReportsQuestionsRoute: AdminReportsQuestionsRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSmsRoute: AdminSmsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBulkImportBatchIdRoute: AdminBulkImportBatchIdRoute,
  AdminBulkImportHistoryRoute: AdminBulkImportHistoryRoute,
  AdminExamsIdRoute: AdminExamsIdRoute,
  AdminExamsNewRoute: AdminExamsNewRoute,
  AdminShopCategoriesRoute: AdminShopCategoriesRoute,
  AdminShopCouponsRoute: AdminShopCouponsRoute,
  AdminShopOrdersRoute: AdminShopOrdersRoute,
  AdminShopProductsRoute: AdminShopProductsRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminBulkImportIndexRoute: AdminBulkImportIndexRoute,
  AdminExamsIndexRoute: AdminExamsIndexRoute,
  AdminShopIndexRoute: AdminShopIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PaymentResultRoute: PaymentResultRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  InviteSlugRoute: InviteSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsletterManageRoute: NewsletterManageRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  ShopSlugRoute: ShopSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  ApiPublicNewsletterDigestProcessQueueRoute:
    ApiPublicNewsletterDigestProcessQueueRoute,
  ApiPublicNewsletterProcessQueueRoute: ApiPublicNewsletterProcessQueueRoute,
  ApiPublicWeeklyProgressProcessQueueRoute:
    ApiPublicWeeklyProgressProcessQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
